addSbtPlugin("com.github.sbt"   % "sbt-native-packager" % "1.11.0")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.13.1")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"       % "2.3.0" )
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.6.4")
addSbtPlugin("org.scala-js"     % "sbt-scalajs"         % "1.18.1")